import type { BonusKesif } from "./bonusKesifler";

/**
 * ÖĞRENME NOKTALARI
 *
 * Ana turdan bağımsız, serbest keşif içeriği. Oyuncu nereye giderse
 * oradaki nesneyi, işi ve olayı öğrenir — sıra beklemez.
 *
 * `tip` alanı mini haritada simge ve renk seçer:
 *   zanaat · kultur · yasam · yapi · doga · tarih
 */

export interface OgrenmeNoktasi extends BonusKesif {
  tip: "zanaat" | "kultur" | "yasam" | "yapi" | "doga" | "tarih";
}

export const OGRENME_NOKTALARI: OgrenmeNoktasi[] = [
  /* ---------- OBA: zanaat ve günlük hayat ---------- */
  { id: "og_ok", ad: "Ok Yapımı", tip: "zanaat", pos: [-25, 1.2, 10],
    metin: "Ok gövdesi düzgün olmalıydı. Tüy yerleşimi uçuşu etkileyebilirdi.",
    kaynakNotu: "Metropolitan Museum, Nomadic Art of the Eastern Eurasian Steppes" },
  { id: "og_yay", ad: "Yay Kurma", tip: "zanaat", pos: [-23, 1.2, 12],
    metin: "Yay birden çok malzemenin birleşiminden yapılabilirdi. Kurmak güç ve teknik isterdi.",
    kaynakNotu: "Metropolitan Museum, Nomadic Art of the Eastern Eurasian Steppes" },
  { id: "og_kece", ad: "Keçe Basma", tip: "zanaat", pos: [-16, 1.1, 15],
    metin: "Yün, su ve emekle keçeye dönüşür. Otağ örtüsü de çizme astarı da bu yolla yapılırdı.",
    kaynakNotu: "Encyclopaedia Iranica, 'Felt', https://www.iranicaonline.org/articles/felt/" },
  { id: "og_deri", ad: "Deri İşleme", tip: "zanaat", pos: [-19, 1.1, 17],
    metin: "Deri tuzlanıp kazınır, sonra yumuşatılırdı. Su tulumu ve çizme bu emekten çıkardı.",
    kaynakNotu: "Encyclopaedia Iranica, 'Central Asia x. Economy Before the Timurids', https://www.iranicaonline.org/articles/central-asia-x/" },
  { id: "og_comlek", ad: "Çömlekçilik", tip: "zanaat", pos: [-14, 1.0, 8],
    metin: "Kap yapmak toprağı tanımayı gerektirir. Pişirme sıcaklığı kabın ömrünü belirlerdi.",
    kaynakNotu: "British Museum, vessel MAS.601, 750–860, https://www.britishmuseum.org/collection/object/A_MAS-601" },
  { id: "og_ahsap", ad: "Ahşap Oyma", tip: "zanaat", pos: [-12, 1.0, 18],
    metin: "Kaşık, çanak ve semer ahşaptan oyulurdu. Damarın yönü kırılmayı belirlerdi.",
    kaynakNotu: "Encyclopaedia Iranica, 'Central Asia x. Economy Before the Timurids', https://www.iranicaonline.org/articles/central-asia-x/" },
  { id: "og_kosum", ad: "At Koşumu", tip: "zanaat", pos: [-9, 1.2, -4],
    metin: "Eyer ve koşum, binicinin dengeli oturmasına yardım edebilir. Biçimler dönem ve bölgeye göre değişir.",
    kaynakNotu: "The Metropolitan Museum of Art, Openwork Fitting, Central Asia, https://www.metmuseum.org/art/collection/search/65326" },
  { id: "og_ip", ad: "İp Bükme", tip: "zanaat", pos: [-6, 1.0, 20],
    metin: "Kıl ve yünden ip bükülürdü. Çadırın gergisi de yükün bağı da ipe emanetti.",
    kaynakNotu: "Encyclopaedia Iranica, 'Central Asia x. Economy Before the Timurids', https://www.iranicaonline.org/articles/central-asia-x/" },
  { id: "og_sut", ad: "Süt ve Kımız", tip: "yasam", pos: [8, 1.1, -3],
    metin: "Kısrak sütü mayalanarak kımıza dönüşürdü. Bekleme süresi tadı belirlerdi.",
    kaynakNotu: "Kondybayev et al., Fermented mare milk product (Qymyz, Koumiss), International Dairy Journal 119 (2021), FAO AGRIS, https://agris.fao.org/search/en/records/65debebf0f3e94b9e5d0dbb3" },
  { id: "og_ekmek", ad: "Hamur ve Ekmek", tip: "yasam", pos: [6, 1.1, 2],
    metin: "Hamur, sıcak bir yüzeyde hızlı pişebilir. Hafif yiyecekler yolculukta taşımayı kolaylaştırır.",
    kaynakNotu: null },
  { id: "og_kurutma", ad: "Et Kurutma", tip: "yasam", pos: [8, 1.2, -1],
    metin: "Et ince dilimlenip kurutulurdu. Kışa hazırlık yaz sonunda başlardı.",
    kaynakNotu: "FAO, Manual on Simple Methods of Meat Preservation, https://www.fao.org/4/x6932e/x6932e02.htm" },
  { id: "og_gures", ad: "Güreş", tip: "kultur", pos: [14, 1.2, -20],
    metin: "Güreş, güç kadar denge ve çeviklik ister. Bu sahne, spor ve talim yönünü gösterir.",
    kaynakNotu: null },
  { id: "og_ategitim", ad: "At Eğitimi", tip: "kultur", pos: [22, 1.3, -26],
    metin: "Genç at sabırla alıştırılırdı. Binici ile hayvan birbirini tanımadan iş görmezdi.",
    kaynakNotu: null },
  { id: "og_oktalim", ad: "Ok Talimi", tip: "kultur", pos: [17, 1.4, -30],
    metin: "Hedefe isabet kadar duruş ve nefes de öğretilirdi.",
    kaynakNotu: null },
  { id: "og_oyun", ad: "Çocuk Oyunları", tip: "kultur", pos: [10, 0.9, 13],
    metin: "Aşık kemikleri oyun taşı olarak kullanılabilir. Oyunun kuralları yer ve zamana göre değişebilir.",
    kaynakNotu: "British Museum, knuckle-bone used in game, Museum no. As1974,15.16.i, https://www.britishmuseum.org/collection/object/W_As1974-15-16-i" },
  { id: "og_muzik", ad: "Müzik ve Ezgi", tip: "kultur", pos: [4, 1.2, 27],
    metin: "Kopuz eşliğinde söylenen destanlar hem eğlendirir hem hatırlatırdı.",
    kaynakNotu: "UNESCO Intangible Cultural Heritage, Heritage of Dede Qorqud/Korkyt Ata/Dede Korkut, https://ich.unesco.org/en/RL/01399" },
  { id: "og_dans", ad: "Halka Oyunu", tip: "kultur", pos: [-2, 1.2, 31],
    metin: "Halka düzeni birlikte hareket etmeyi kolaylaştırır. Adımlar, duyulan ezgiye göre değişebilir.",
    kaynakNotu: null },
  { id: "og_dugun", ad: "Düğün Hazırlığı", tip: "kultur", pos: [-5, 1.1, 24],
    metin: "Düğün iki obayı birbirine bağlardı. Hazırlık günler önce başlardı.",
    kaynakNotu: "UNESCO Intangible Cultural Heritage, Heritage of Dede Qorqud/Korkyt Ata/Dede Korkut, https://ich.unesco.org/en/RL/01399" },
  /* ---------- PAZARYERİ ---------- */
  { id: "og_pz_takas", ad: "Takas Düzeni", tip: "yasam", pos: [44, 1.2, -38],
    metin: "Bazı alışverişlerde mallar doğrudan değiştirilebilir. Değişimin biçimi, yer ve zamana göre farklılaşabilir.",
    kaynakNotu: "UNESCO, About the Silk Roads, https://www.unesco.org/en/silk-roads/about-silk-roads" },
  { id: "og_pz_kervan", ad: "Kervan Yolu", tip: "yasam", pos: [50, 1.3, -36],
    metin: "Uzaktan gelen mal, uzaktan gelen haber demekti. Pazar bilgi de taşırdı.",
    kaynakNotu: "UNESCO, About the Silk Roads, https://www.unesco.org/en/silk-roads/about-silk-roads" },
  { id: "og_pz_hayvan", ad: "Hayvan Pazarı", tip: "yasam", pos: [60, 1.4, -46],
    metin: "Dişler hayvanın yaklaşık yaşına dair ipucu verebilir. Tek inceleme kesin sonuç sağlamaz.",
    kaynakNotu: "Rutgers NJAES Cooperative Extension, Farm Animal Dentition - What Teeth Can Tell You, Publication E351, 2017, https://njaes.rutgers.edu/pubs/publication.php?pid=E351" },
  { id: "og_pz_olcu", ad: "Ölçü ve Tartı", tip: "yasam", pos: [47, 1.1, -33],
    metin: "Tartı ve ölçü, alışverişte karşılaştırma sağlar. Kullanılan birimler dönem ve bölgeye göre değişebilir.",
    kaynakNotu: "Dönemsel ölçü birimleri için birincil kaynak bulunamadı; metin karşılaştırma diliyle yazıldı." },
  { id: "og_pz_ipek", ad: "Uzak Diyar Malları", tip: "kultur", pos: [52, 1.2, -30],
    metin: "İpek ve başka uzak mallar farklı yollarla taşınabilirdi. Mallarla birlikte bilgiler ve alışkanlıklar da dolaşırdı.",
    kaynakNotu: "UNESCO, About the Silk Roads, https://www.unesco.org/en/silk-roads/about-silk-roads" },
  { id: "og_pz_han", ad: "Kervan Konağı", tip: "yapi", pos: [57, 1.4, -27],
    metin: "Yolcular konaklama yerlerinde dinlenebilirdi. Bu alanlar, mal ve haber alışverişini kolaylaştırabilirdi.",
    kaynakNotu: "UNESCO, About the Silk Roads, https://www.unesco.org/en/silk-roads/about-silk-roads" },
  /* ---------- BALBAL SIRTI ---------- */
  { id: "og_bs_dikme", ad: "Taş Dikme", tip: "tarih", pos: [-52, 1.6, 58],
    metin: "Taş dikmek hatırlamanın en dayanıklı biçimiydi. Yazı olmasa da iz kalırdı.",
    kaynakNotu: "UNESCO World Heritage Centre, Orkhon Valley Cultural Landscape nomination documents, https://whc.unesco.org/en/list/1081/documents/" },
  { id: "og_bs_kase", ad: "Kâse Tutan El", tip: "tarih", pos: [-49, 1.8, 55],
    metin: "Bazı figürlerin elinde kap benzeri biçim görülür. Bunun anlamı kesin olarak bilinmiyor.",
    kaynakNotu: "UNESCO World Heritage Centre, Orkhon Valley Cultural Landscape nomination documents, https://whc.unesco.org/en/list/1081/documents/" },
  { id: "og_bs_yonu", ad: "Taşların Yönü", tip: "tarih", pos: [-55, 1.5, 62],
    metin: "Figürlerin baktığı yön dikkatle kaydedilir. Yalnız yön bilgisi, yapılış amacını açıklamaya yetmez.",
    kaynakNotu: "U.S. National Park Service, What Is Archeological Context?, https://www.nps.gov/articles/000/what-is-archeological-context.htm" },
  { id: "og_bs_asinma", ad: "Aşınma", tip: "doga", pos: [-58, 1.5, 66],
    metin: "Rüzgâr ve yağmur taşı yontar. Aşınma, taşın yaşı hakkında ipucu verir.",
    kaynakNotu: null },
  { id: "og_bs_liken", ad: "Liken", tip: "doga", pos: [-61, 1.3, 64],
    metin: "Taş üzerindeki liken yavaş büyür. Kapladığı alan zaman ölçüsü olabilir.",
    kaynakNotu: null },
  { id: "og_bs_obo", ad: "Yol Taşları", tip: "kultur", pos: [-46, 1.3, 50],
    metin: "Yol kenarında küçük bir taş yığını görülüyor. Onu kimin ve neden yaptığı bilinmiyor.",
    kaynakNotu: null },
  { id: "og_bs_ruzgar", ad: "Sırtın Rüzgârı", tip: "doga", pos: [-63, 1.6, 70],
    metin: "Yüksek yerde rüzgâr sürekli eser. Bu yüzden sırtlarda kalıcı yerleşim kurulmazdı.",
    kaynakNotu: null },
  { id: "og_bs_manzara", ad: "Gözetleme", tip: "yasam", pos: [-66, 1.8, 72],
    metin: "Yüksek noktadan uzak çevre daha kolay görülebilir. Bu görüş, yol ve hareketleri izlemeye yardım eder.",
    kaynakNotu: null },
  /* ---------- SU BAŞI ---------- */
  { id: "og_su_sira", ad: "Su Sırası", tip: "yasam", pos: [60, 1.2, 26],
    metin: "Sahnedeki insanlar su başında sırayla ilerliyor. Öncelik düzeni topluluktan topluluğa değişebilir.",
    kaynakNotu: null },
  { id: "og_su_sogut", ad: "Söğüt", tip: "doga", pos: [56, 1.6, 32],
    metin: "Söğüt hem gölge hem esneklik verir. Dalları sepet ve çit örmede kullanılabilirdi.",
    kaynakNotu: null },
  { id: "og_su_saz", ad: "Sazlık", tip: "zanaat", pos: [58, 1.0, 34],
    metin: "Saz lifleri hasır ve sepet yapımında kullanılabilir. Kullanım biçimi bölgeye göre değişebilir.",
    kaynakNotu: null },
  { id: "og_su_iz", ad: "Çamurdaki İzler", tip: "tarih", pos: [62, 0.9, 20],
    metin: "Islak toprak izi saklar. Kimin ne zaman geçtiği izlerden okunabilirdi.",
    kaynakNotu: null },
  { id: "og_su_taskin", ad: "Taşkın Çizgisi", tip: "doga", pos: [52, 1.1, 36],
    metin: "Kıyıdaki taş çizgisi önceki su yükselmelerini gösterebilir. D01 kamplarındaki kullanım biçimini bilmiyoruz.",
    kaynakNotu: null },
  { id: "og_su_balik", ad: "Su Ürünleri", tip: "yasam", pos: [66, 1.0, 22],
    metin: "Akarsuda balık bulunabilir. Bu sahne, beslenmenin çevreye göre değişebileceğini gösterir.",
    kaynakNotu: null },
  { id: "og_su_gecit", ad: "Sığ Geçit", tip: "yasam", pos: [70, 1.0, 12],
    metin: "Dere belli yerlerden geçilirdi. Geçit bilgisi yol bilgisinin parçasıydı.",
    kaynakNotu: null },
  { id: "og_su_kimiz", ad: "Serinletme", tip: "yasam", pos: [64, 1.1, 28],
    metin: "Kaplar suya batırılarak serin tutulurdu. Yaz sıcağında bu bir zorunluluktu.",
    kaynakNotu: null },
  /* ---------- ESKİ YURT YERİ ---------- */
  { id: "og_ey_iskelet", ad: "Otağ İskeleti", tip: "yapi", pos: [-34, 1.6, -66],
    metin: "Ahşap kafesin bir bölümü ayakta kalmış. Örtünün ne zaman kaldırıldığını görünüşten bilemeyiz.",
    kaynakNotu: null },
  { id: "og_ey_kul", ad: "Ocak Külü", tip: "tarih", pos: [-30, 0.9, -64],
    metin: "Sönmüş ocak kimsenin kalmadığını gösterir. Kül dağılır ama taş kalır.",
    kaynakNotu: null },
  { id: "og_ey_katman", ad: "Toprak Katmanları", tip: "tarih", pos: [-38, 1.0, -72],
    metin: "Toprak katman katman birikir. Alt katman daha eskidir; kazı bunu okur.",
    kaynakNotu: "U.S. National Park Service, What Is Archeological Context?, https://www.nps.gov/articles/000/what-is-archeological-context.htm" },
  { id: "og_ey_seramik", ad: "Seramik Parçası", tip: "tarih", pos: [-36, 0.9, -68],
    metin: "Kırık çanak bile bilgi taşır. Hamuru ve bezemesi dönemi anlatabilir.",
    kaynakNotu: "U.S. National Park Service, What Is Archeological Context?, https://www.nps.gov/articles/000/what-is-archeological-context.htm" },
  { id: "og_ey_hoyuk", ad: "Höyük", tip: "tarih", pos: [-40, 2.0, -80],
    metin: "Üst üste kurulan yerleşimler tepe oluşturur. Höyük, zamanın yığılmış hâlidir.",
    kaynakNotu: null },
  { id: "og_ey_duvar", ad: "Yıkık Duvar", tip: "yapi", pos: [-44, 1.4, -76],
    metin: "Taş duvar, daha kalıcı bir yapının izi olabilir. Tek başına kullanım tarihini göstermez.",
    kaynakNotu: "U.S. National Park Service, What Is Archeological Context?, https://www.nps.gov/articles/000/what-is-archeological-context.htm" },
  { id: "og_ey_donus", ad: "Geri Dönüş", tip: "kultur", pos: [-32, 1.2, -70],
    metin: "Bazı topluluklar mevsimlik yolları yeniden kullanmış olabilir. Aynı yere dönüş, her toplulukta aynı biçimde gerçekleşmez.",
    kaynakNotu: "UNESCO World Heritage Centre, Orkhon Valley Cultural Landscape, https://whc.unesco.org/en/list/1081/" },
  { id: "og_ey_koruma", ad: "Yerinde Bırakmak", tip: "tarih", pos: [-36, 1.0, -74],
    metin: "Buluntu yerinden alınırsa bağlamı kaybolur. Bilgi çoğu zaman yerinde saklıdır.",
    kaynakNotu: "U.S. National Park Service, What Is Archeological Context?, https://www.nps.gov/articles/000/what-is-archeological-context.htm" },
  /* ---------- GİRİLEBİLİR OTAĞLAR ---------- */
  { id: "og_ot_hakan", ad: "Hakan Otağı", tip: "yapi", pos: [0, 2.4, 20],
    metin: "Büyük otağın merkezde bulunması yöneticilik işareti olabilir. D01 yerleşim hiyerarşisini kesin bilmiyoruz.",
    kaynakNotu: null },
  { id: "og_ot_bey1", ad: "Bey Otağı", tip: "yapi", pos: [46, 2.0, -30],
    metin: "Kırmızı örtü ve tuğ sorumluluk işareti olabilir. D01 dönemindeki anlamlarını kesin bilmiyoruz.",
    kaynakNotu: null },
  { id: "og_ot_bey2", ad: "Sırt Beyinin Otağı", tip: "yapi", pos: [-44, 2.0, 72],
    metin: "Yüksek yerdeki otağ hem uzağı görür hem uzaktan görünürdü.",
    kaynakNotu: null },
  { id: "og_ot_usta", ad: "Usta Otağı", tip: "zanaat", pos: [70, 2.0, 26],
    metin: "Otağ hem yaşam hem çalışma alanı olmuş olabilir. Tezgâhın kesin yerini bilmiyoruz.",
    kaynakNotu: null },
  { id: "og_ot_ic", ad: "Otağın İçi", tip: "yasam", pos: [-27, 1.8, -14],
    metin: "Sahnede ocak ortada, yataklar kenarda gösteriliyor. Bu düzen belirli bir otağı temsil etmiyor.",
    kaynakNotu: "Sahne temsilîdir; belirli bir arkeolojik otağ planına dayanmaz." },
  { id: "og_ot_besik", ad: "Beşik", tip: "yasam", pos: [36, 1.6, 23],
    metin: "Beşik sıcak ve korunaklı bir yere konmuş olabilir. D01 otağındaki yerini bilmiyoruz.",
    kaynakNotu: null },
  /* ---------- ORDUGÂH ---------- */
  { id: "og_or_duzen", ad: "Ordugâh Düzeni", tip: "yapi", pos: [4, 1.6, -66],
    metin: "Çadırlar bu sahnede sıra sıra kurulmuş. Düzen, görev alanlarını ayırmayı kolaylaştırabilir.",
    kaynakNotu: "Ordugâh düzeni temsilîdir; D01 dönemine ait plan kaynağı bulunamadı." },
  { id: "og_or_onluk", ad: "Onlu Düzen", tip: "kultur", pos: [14, 1.5, -62],
    metin: "Bazı topluluklarda onlu gruplar kullanıldığı düşünülür. D01 düzeninin ayrıntılarını kesin bilmiyoruz.",
    kaynakNotu: null },
  { id: "og_or_yay", ad: "Kompozit Yay", tip: "zanaat", pos: [10, 1.6, -50],
    metin: "Yay birden çok malzemenin birleşiminden yapılırdı. Nemden korunması gerekirdi.",
    kaynakNotu: "The Metropolitan Museum of Art, Nomadic Art of the Eastern Eurasian Steppes" },
  { id: "og_or_atli", ad: "Atlı Talim", tip: "kultur", pos: [22, 1.8, -58],
    metin: "At üstünde ok atmak denge ve tekrar ister. Bu sahne, talim sürecini gösterir.",
    kaynakNotu: "The Metropolitan Museum of Art, Nomadic Art of the Eastern Eurasian Steppes, https://www.metmuseum.org/exhibitions/listings/2002/nomadic-art" },
  { id: "og_or_nobet", ad: "Nöbet Kulesi", tip: "yapi", pos: [10, 4.6, -60],
    metin: "Yüksek bir platform çevreyi gözlemlemeyi kolaylaştırabilir. D01 ordugâhındaki kule biçimini bilmiyoruz.",
    kaynakNotu: null },
  { id: "og_or_sancak", ad: "Tuğ ve Sancak", tip: "kultur", pos: [10, 3.4, -46],
    metin: "Tuğ ve sancaklar uzaktan seçilen işaretlerdir. Bu dönemdeki sayıları ve anlamları kesin bilinmiyor.",
    kaynakNotu: null },
  { id: "og_or_at", ad: "Savaş Atı", tip: "yasam", pos: [-14, 1.6, -56],
    metin: "Atların koşumu, yemi ve dinlenmesi düzenli kontrol gerektirir. Kullanılan donanım dönem ve bölgeye göre değişir.",
    kaynakNotu: "The Metropolitan Museum of Art, Openwork Fitting, Central Asia, https://www.metmuseum.org/art/collection/search/65326" },
  { id: "og_or_haber", ad: "Haberleşme", tip: "kultur", pos: [16, 2.0, -52],
    metin: "Haberler yolcular veya ulaklar aracılığıyla taşınmış olabilir. Düzenli menzil sistemi burada varsayılmıyor.",
    kaynakNotu: "UNESCO, About the Silk Roads, https://www.unesco.org/en/silk-roads/about-silk-roads" },
  { id: "og_or_zirh", ad: "Koruyucu Donanım", tip: "zanaat", pos: [6, 1.6, -48],
    metin: "Koruyucu donanım farklı malzemeleri birleştirebilir. Sahnedeki biçim belirli bir eseri kopyalamaz.",
    kaynakNotu: "The Metropolitan Museum of Art, Nomadic Art of the Eastern Eurasian Steppes, https://www.metmuseum.org/exhibitions/listings/2002/nomadic-art" },
  { id: "og_or_savas", ad: "Savaş Yalnız Değildir", tip: "tarih", pos: [10, 1.8, -70],
    metin: "Bir topluluk yalnız savaşla anlaşılmaz. Zanaat, ticaret ve göç de tarihin parçasıdır.",
    kaynakNotu: null },
  /* ---------- OTAĞ ÇEVRESİ (ChatGPT teslimi) ---------- */
  { id: "oc_et_01", ad: "Havanın Yolu", tip: "yasam", pos: [-138.7, 1.3, 100.8],
    metin: "İnce et parçaları, havanın dolaşabileceği aralıklarla asılmış. Böylece yüzeyler birbirine değmeden kuruyabilir.",
    kaynakNotu: null },
  { id: "oc_et_02", ad: "Suyun Azalması", tip: "yasam", pos: [132.7, 1.3, 94.2],
    metin: "Kurutma, etin içindeki suyu azaltarak saklamayı kolaylaştırır. Süre, hava sıcaklığına ve neme göre değişir.",
    kaynakNotu: "FAO, Manual on Simple Methods of Meat Preservation, https://www.fao.org/4/x6932e/x6932e02.htm" },
  { id: "oc_et_03", ad: "Hasırın İşlevi", tip: "yasam", pos: [166.9, 1.3, -25.6],
    metin: "Hasır, parçaları topraktan uzak tutan temiz bir yüzey olabilir. Kullanılan yüzey düzenli temizlenmelidir.",
    kaynakNotu: "FAO, Manual on Simple Methods of Meat Preservation, https://www.fao.org/4/x6932e/x6932e02.htm" },
  { id: "oc_et_04", ad: "Tuz ve Nem", tip: "yasam", pos: [72.3, 1.3, 174.9],
    metin: "Tuz, bazı kurutma yöntemlerinde nem kaybını destekler. Miktar, ürünün tadını ve dayanıklılığını etkiler.",
    kaynakNotu: "FAO, Manual on Simple Methods of Meat Preservation, https://www.fao.org/4/x6932e/x6932e02.htm" },
  { id: "oc_et_05", ad: "Kurut Topakları", tip: "yasam", pos: [7.7, 1.3, 202.8],
    metin: "Kurut topakları, fermente süt ürünlerinin kurutulmuş biçimlerindendir. Kurutma, taşımayı ve saklamayı kolaylaştırabilir.",
    kaynakNotu: "FAO, The Technology of Traditional Milk Products in Developing Countries, Asia section, https://www.fao.org/4/t0251e/T0251E14.htm" },
  { id: "oc_et_06", ad: "Paylaşım Düzeni", tip: "yasam", pos: [198.7, 1.3, 76.7],
    metin: "Yiyecekler aileler arasında paylaşılmış olabilir. D01 dağıtım düzenini kesin bilmiyoruz.",
    kaynakNotu: null },
  { id: "oc_soh_01", ad: "Göz Göze Halka", tip: "kultur", pos: [-144.9, 1.3, 81.6],
    metin: "Minderler bir halka oluşturuyor. Bu düzen, konuşanların birbirini görmesini kolaylaştırır.",
    kaynakNotu: null },
  { id: "oc_soh_02", ad: "Ortadaki İkram", tip: "kultur", pos: [-191.3, 1.3, -22.1],
    metin: "Ortadaki kap, ikramın ortak alanda sunulduğunu düşündürebilir. İçeriğini yalnız görünüşten bilemeyiz.",
    kaynakNotu: null },
  { id: "oc_soh_03", ad: "Haberlerin Dolaşımı", tip: "kultur", pos: [153.7, 1.3, -34.5],
    metin: "Pazarlar ve konak yerleri haberlerin dolaştığı buluşma noktaları olabilir. Her haber aynı güvenilirliği taşımaz.",
    kaynakNotu: "UNESCO World Heritage Centre, Orkhon Valley Cultural Landscape, Property 1081, https://whc.unesco.org/en/list/1081/" },
  { id: "oc_soh_04", ad: "Dinleyerek Öğrenmek", tip: "kultur", pos: [69.3, 1.3, 177.2],
    metin: "Çocuklar konuşmaları dinleyerek yeni sözler öğrenmiş olabilir. Katılım biçimlerini kesin bilmiyoruz.",
    kaynakNotu: null },
  { id: "oc_soh_05", ad: "Paylaşılan Kararlar", tip: "kultur", pos: [-226.2, 1.3, 62.3],
    metin: "Kadınlar ve erkekler günlük kararları farklı biçimlerde paylaşmış olabilir. Roller, kaynaklar incelenmeden kesinleştirilmemelidir.",
    kaynakNotu: null },
  { id: "oc_soh_06", ad: "Misafir Minderi", tip: "kultur", pos: [182.9, 1.3, 59.0],
    metin: "Misafir için ayrı minder bırakılmış olabilir. Oturma sırasının anlamını kesin bilmiyoruz.",
    kaynakNotu: null },
  { id: "oc_sut_01", ad: "Temiz Kap", tip: "yasam", pos: [-165.7, 1.3, 78.5],
    metin: "Sağım kabı temiz tutulmazsa süt çabuk bozulabilir. Kapların durulanması, ürünün korunmasına yardım eder.",
    kaynakNotu: null },
  { id: "oc_sut_02", ad: "Yayıkta Dönüşüm", tip: "yasam", pos: [-174.9, 1.3, -39.8],
    metin: "Yayıkta çalkalanan süt ürünü, yağın ayrılmasını sağlayabilir. Bu işlem tereyağı üretiminin temelidir.",
    kaynakNotu: "FAO, The Technology of Traditional Milk Products in Developing Countries, Butter section, https://www.fao.org/4/t0251e/t0251e15.htm" },
  { id: "oc_sut_03", ad: "Kımızın Oluşumu", tip: "yasam", pos: [-95.9, 1.3, 165.3],
    metin: "Kısrak sütü mayalanınca kımız oluşabilir. Tat, süreye ve kullanılan mayaya göre değişir.",
    kaynakNotu: "FAO AGRIS, Kondybayev et al., Fermented Mare Milk Product (Qymyz, Koumiss), 2021, https://agris.fao.org/search/en/records/65debebf0f3e94b9e5d0dbb3" },
  { id: "oc_sut_04", ad: "Sağım Zamanı", tip: "yasam", pos: [72.2, 1.3, 187.7],
    metin: "Sağım zamanı, hayvanın durumuna göre ayarlanır. Yavrunun beslenmesi de dikkate alınmalıdır.",
    kaynakNotu: null },
  { id: "oc_sut_05", ad: "Sütün Yolları", tip: "yasam", pos: [-195.3, 1.3, 46.5],
    metin: "Süt farklı kaplara ayrılarak işlenebilir. Bazısı içilir, bazısı başka ürünlere dönüşür.",
    kaynakNotu: "FAO, The Technology of Traditional Milk Products in Developing Countries, Asia section, https://www.fao.org/4/t0251e/T0251E14.htm" },
  { id: "oc_sut_06", ad: "Hayvanı Tanımak", tip: "yasam", pos: [-131.9, 1.3, -106.9],
    metin: "Her hayvanın davranışı ve sütü aynı değildir. Sağım yapan kişi, hayvanı dikkatle tanır.",
    kaynakNotu: null },
  { id: "oc_ota_01", ad: "Gölgelik Alan", tip: "yasam", pos: [118.6, 1.3, 92.9],
    metin: "Gölgelik, otağ önünde serin bir çalışma alanı oluşturur. Güneş yönü değiştikçe gölge de yer değiştirir.",
    kaynakNotu: null },
  { id: "oc_ota_02", ad: "Yakındaki Beşik", tip: "yasam", pos: [-145.3, 1.3, -32.3],
    metin: "Beşik günlük işlerin yakınında tutulmuş olabilir. D01 otağındaki kesin konumunu bilmiyoruz.",
    kaynakNotu: null },
  { id: "oc_ota_03", ad: "Kapının Yönü", tip: "yasam", pos: [-98.6, 1.3, 181.0],
    metin: "Kapının yönü, rüzgâr ve kullanım düzeniyle ilişkili olabilir. D01 uygulaması ayrıca doğrulanmalıdır.",
    kaynakNotu: null },
  { id: "oc_ota_04", ad: "Eşyanın Yeri", tip: "yasam", pos: [-9.6, 1.3, 209.8],
    metin: "Kaplar ve dokumalar farklı yerlere konmuş olabilir. D01 eşya düzenini kesin bilmiyoruz.",
    kaynakNotu: null },
  { id: "oc_ota_05", ad: "Su Tulumu", tip: "yasam", pos: [-234.1, 1.3, 63.9],
    metin: "Deri tulum, sıvı taşımak için kullanılabilir. Dikiş ve ağız kısmı sızdırmazlığı etkiler.",
    kaynakNotu: null },
  { id: "oc_ota_06", ad: "Komşuluk Emeği", tip: "yasam", pos: [-138.9, 1.3, -134.7],
    metin: "Komşu otağlar arasında araç ve emek paylaşılmış olabilir. İlişkinin biçimi topluluktan topluluğa değişebilir.",
    kaynakNotu: "UNESCO World Heritage Centre, Orkhon Valley Cultural Landscape, Property 1081, https://whc.unesco.org/en/list/1081/" },
  { id: "oc_yun_01", ad: "Lifleri Açmak", tip: "zanaat", pos: [138.9, 1.3, 80.6],
    metin: "Yün önce ayrılır ve temizlenir. Dolaşmış lifler açıldıkça eğirme kolaylaşır.",
    kaynakNotu: null },
  { id: "oc_yun_02", ad: "İğin Dönüşü", tip: "zanaat", pos: [192.4, 1.3, -39.2],
    metin: "İğ ağırlaştıkça daha düzenli dönebilir. Dönüş, lifleri birbirine sararak ip oluşturur.",
    kaynakNotu: "The Metropolitan Museum of Art, Spindle Whorl, 9th–10th century, Object 38.40.1, https://www.metmuseum.org/art/collection/search/449217" },
  { id: "oc_yun_03", ad: "İpliğin Kalınlığı", tip: "zanaat", pos: [-103.0, 1.3, 160.5],
    metin: "İplik kalınlığı ve boyama yöntemi kullanım amacına göre değişmiş olabilir. D01 tercihlerini kesin bilmiyoruz.",
    kaynakNotu: null },
  { id: "oc_yun_04", ad: "Renklerin Kaynağı", tip: "zanaat", pos: [4.9, 1.3, 217.2],
    metin: "Doğal yün renkleri ipliğe çeşitlilik verir. Boyama varsa malzeme ve yöntem ayrıca incelenmelidir.",
    kaynakNotu: null },
  { id: "oc_yun_05", ad: "İplikten Dokumaya", tip: "zanaat", pos: [187.9, 1.3, 49.1],
    metin: "Eğrilen ip, dokuma için hazırlanır. Bir kilim, sayısız ipin düzenli birleşmesiyle oluşur.",
    kaynakNotu: "The Metropolitan Museum of Art, Spindle Whorl, 9th–10th century, Object 38.40.1, https://www.metmuseum.org/art/collection/search/449217; The Metropolitan Museum of Art, Textile with Confronted Horses in Roundels, 8th–9th century, Object 2006.173, https://www.metmuseum.org/art/collection/search/73207" },
  { id: "oc_yun_06", ad: "Paylaşılan Beceri", tip: "zanaat", pos: [-145.0, 1.3, -121.6],
    metin: "Yün işi farklı yaşlardaki kişilerin katkısıyla ilerleyebilir. Sahnede görevler beceriye göre paylaşılabilir.",
    kaynakNotu: null },
];

export const OGRENME_TOPLAM = OGRENME_NOKTALARI.length;
