import type { BonusKesif } from "./bonusKesifler";

/**
 * ÖĞRENME NOKTALARI
 *
 * Ana turdan bağımsız, serbest keşif içeriği. Oyuncu nereye giderse
 * oradaki nesneyi, işi ve olayı öğrenir — sıra beklemez.
 *
 * `tip` alanı mini haritada simge ve renk seçer:
 *   zanaat · kultur · yasam · yapi · doga · tarih
 */

export interface OgrenmeNoktasi extends BonusKesif {
  tip: "zanaat" | "kultur" | "yasam" | "yapi" | "doga" | "tarih";
}

export const OGRENME_NOKTALARI: OgrenmeNoktasi[] = [
  /* ---------- OBA: zanaat ve günlük hayat ---------- */
  { id: "og_ok", ad: "Ok Yapımı", tip: "zanaat", pos: [-25, 1.2, 10],
    metin: "Ok gövdesi düzgün olmalıydı. Tüy yerleşimi uçuşu etkileyebilirdi.",
    kaynakNotu: "Metropolitan Museum, Nomadic Art of the Eastern Eurasian Steppes" },
  { id: "og_yay", ad: "Yay Kurma", tip: "zanaat", pos: [-23, 1.2, 12],
    metin: "Yay birden çok malzemenin birleşiminden yapılabilirdi. Kurmak güç ve teknik isterdi.",
    kaynakNotu: "Metropolitan Museum, Nomadic Art of the Eastern Eurasian Steppes" },
  { id: "og_kece", ad: "Keçe Basma", tip: "zanaat", pos: [-16, 1.1, 15],
    metin: "Yün, su ve emekle keçeye dönüşür. Otağ örtüsü de çizme astarı da bu yolla yapılırdı.",
    kaynakNotu: null },
  { id: "og_deri", ad: "Deri İşleme", tip: "zanaat", pos: [-19, 1.1, 17],
    metin: "Deri tuzlanıp kazınır, sonra yumuşatılırdı. Su tulumu ve çizme bu emekten çıkardı.",
    kaynakNotu: null },
  { id: "og_comlek", ad: "Çömlekçilik", tip: "zanaat", pos: [-14, 1.0, 8],
    metin: "Kap yapmak toprağı tanımayı gerektirir. Pişirme sıcaklığı kabın ömrünü belirlerdi.",
    kaynakNotu: null },
  { id: "og_ahsap", ad: "Ahşap Oyma", tip: "zanaat", pos: [-12, 1.0, 18],
    metin: "Kaşık, çanak ve semer ahşaptan oyulurdu. Damarın yönü kırılmayı belirlerdi.",
    kaynakNotu: null },
  { id: "og_kosum", ad: "At Koşumu", tip: "zanaat", pos: [-9, 1.2, -4],
    metin: "Eyer ve üzengi binicinin dengesini değiştirir. At üstünde iş yapmayı kolaylaştırırdı.",
    kaynakNotu: "DOĞRULANMALI — üzengi kullanımının dönemi bölgeye göre değişir" },
  { id: "og_ip", ad: "İp Bükme", tip: "zanaat", pos: [-6, 1.0, 20],
    metin: "Kıl ve yünden ip bükülürdü. Çadırın gergisi de yükün bağı da ipe emanetti.",
    kaynakNotu: null },
  { id: "og_sut", ad: "Süt ve Kımız", tip: "yasam", pos: [8, 1.1, -3],
    metin: "Kısrak sütü mayalanarak kımıza dönüşürdü. Bekleme süresi tadı belirlerdi.",
    kaynakNotu: "DOĞRULANMALI — hazırlama yöntemi kaynakla eşleştirilmeli" },
  { id: "og_ekmek", ad: "Hamur ve Ekmek", tip: "yasam", pos: [6, 1.1, 2],
    metin: "Hamur sacda hızla pişerdi. Göç eden bir toplulukta hafif ve dayanıklı yiyecek önemliydi.",
    kaynakNotu: null },
  { id: "og_kurutma", ad: "Et Kurutma", tip: "yasam", pos: [8, 1.2, -1],
    metin: "Et ince dilimlenip kurutulurdu. Kışa hazırlık yaz sonunda başlardı.",
    kaynakNotu: null },
  { id: "og_gures", ad: "Güreş", tip: "kultur", pos: [14, 1.2, -20],
    metin: "Güreş güç kadar denge işiydi. Toplu şölenlerde seyredilirdi.",
    kaynakNotu: null },
  { id: "og_ategitim", ad: "At Eğitimi", tip: "kultur", pos: [22, 1.3, -26],
    metin: "Genç at sabırla alıştırılırdı. Binici ile hayvan birbirini tanımadan iş görmezdi.",
    kaynakNotu: null },
  { id: "og_oktalim", ad: "Ok Talimi", tip: "kultur", pos: [17, 1.4, -30],
    metin: "Hedefe isabet kadar duruş ve nefes de öğretilirdi.",
    kaynakNotu: null },
  { id: "og_oyun", ad: "Çocuk Oyunları", tip: "kultur", pos: [10, 0.9, 13],
    metin: "Aşık kemikleriyle oynanırdı. Oyun sırayı beklemeyi öğretirdi.",
    kaynakNotu: null },
  { id: "og_muzik", ad: "Müzik ve Ezgi", tip: "kultur", pos: [4, 1.2, 27],
    metin: "Kopuz eşliğinde söylenen destanlar hem eğlendirir hem hatırlatırdı.",
    kaynakNotu: null },
  { id: "og_dans", ad: "Halka Oyunu", tip: "kultur", pos: [-2, 1.2, 31],
    metin: "Halka kurulur, ayak vuruşları ezgiye eşlik ederdi.",
    kaynakNotu: null },
  { id: "og_dugun", ad: "Düğün Hazırlığı", tip: "kultur", pos: [-5, 1.1, 24],
    metin: "Düğün iki obayı birbirine bağlardı. Hazırlık günler önce başlardı.",
    kaynakNotu: null },
  /* ---------- PAZARYERİ ---------- */
  { id: "og_pz_takas", ad: "Takas Düzeni", tip: "yasam", pos: [44, 1.2, -38],
    metin: "Para her zaman kullanılmazdı. Deri, at ve dokuma karşılıklı değiştirilebilirdi.",
    kaynakNotu: null },
  { id: "og_pz_kervan", ad: "Kervan Yolu", tip: "yasam", pos: [50, 1.3, -36],
    metin: "Uzaktan gelen mal, uzaktan gelen haber demekti. Pazar bilgi de taşırdı.",
    kaynakNotu: null },
  { id: "og_pz_hayvan", ad: "Hayvan Pazarı", tip: "yasam", pos: [60, 1.4, -46],
    metin: "Alıcı hayvanın dişine ve ayağına bakardı. Yaş ve sağlık böyle anlaşılırdı.",
    kaynakNotu: null },
  { id: "og_pz_olcu", ad: "Ölçü ve Tartı", tip: "yasam", pos: [47, 1.1, -33],
    metin: "Tartı ve ölçü güven meselesiydi. Anlaşmazlık pazar büyüğüne götürülürdü.",
    kaynakNotu: "DOĞRULANMALI — dönemsel ölçü birimleri kaynakla eşleştirilmeli" },
  { id: "og_pz_ipek", ad: "Uzak Diyar Malları", tip: "kultur", pos: [52, 1.2, -30],
    metin: "İpek, baharat ve cam uzaktan gelirdi. Bunlar aynı zamanda başka kültürlerin izidir.",
    kaynakNotu: null },
  { id: "og_pz_han", ad: "Kervan Konağı", tip: "yapi", pos: [57, 1.4, -27],
    metin: "Yolcular geceyi burada geçirirdi. Konak hem barınak hem haber merkeziydi.",
    kaynakNotu: null },
  /* ---------- BALBAL SIRTI ---------- */
  { id: "og_bs_dikme", ad: "Taş Dikme", tip: "tarih", pos: [-52, 1.6, 58],
    metin: "Taş dikmek hatırlamanın en dayanıklı biçimiydi. Yazı olmasa da iz kalırdı.",
    kaynakNotu: null },
  { id: "og_bs_kase", ad: "Kâse Tutan El", tip: "tarih", pos: [-49, 1.8, 55],
    metin: "Bazı figürlerin elinde kap görülür. Anlamı üzerine farklı görüşler vardır.",
    kaynakNotu: "DOĞRULANMALI — ikonografi yorumu uzman onayı gerektirir" },
  { id: "og_bs_yonu", ad: "Taşların Yönü", tip: "tarih", pos: [-55, 1.5, 62],
    metin: "Figürlerin baktığı yön rastgele olmayabilir. Araştırmacılar bunu tartışır.",
    kaynakNotu: "DOĞRULANMALI" },
  { id: "og_bs_asinma", ad: "Aşınma", tip: "doga", pos: [-58, 1.5, 66],
    metin: "Rüzgâr ve yağmur taşı yontar. Aşınma, taşın yaşı hakkında ipucu verir.",
    kaynakNotu: null },
  { id: "og_bs_liken", ad: "Liken", tip: "doga", pos: [-61, 1.3, 64],
    metin: "Taş üzerindeki liken yavaş büyür. Kapladığı alan zaman ölçüsü olabilir.",
    kaynakNotu: null },
  { id: "og_bs_obo", ad: "Yol Taşları", tip: "kultur", pos: [-46, 1.3, 50],
    metin: "Yol kenarındaki taş yığınları yön gösterirdi. Geçen yolcu bir taş eklerdi.",
    kaynakNotu: null },
  { id: "og_bs_ruzgar", ad: "Sırtın Rüzgârı", tip: "doga", pos: [-63, 1.6, 70],
    metin: "Yüksek yerde rüzgâr sürekli eser. Bu yüzden sırtlarda kalıcı yerleşim kurulmazdı.",
    kaynakNotu: null },
  { id: "og_bs_manzara", ad: "Gözetleme", tip: "yasam", pos: [-66, 1.8, 72],
    metin: "Yüksek noktadan uzağı görmek güvenlik demekti. Sırtlar gözcü yeriydi.",
    kaynakNotu: null },
  /* ---------- SU BAŞI ---------- */
  { id: "og_su_sira", ad: "Su Sırası", tip: "yasam", pos: [60, 1.2, 26],
    metin: "Su başında sıra vardı. Önce hayvanlar sulanır, sonra kaplar doldurulurdu.",
    kaynakNotu: null },
  { id: "og_su_sogut", ad: "Söğüt", tip: "doga", pos: [56, 1.6, 32],
    metin: "Söğüt hem gölge hem esneklik verir. Dalları sepet ve çit örmede kullanılabilirdi.",
    kaynakNotu: null },
  { id: "og_su_saz", ad: "Sazlık", tip: "zanaat", pos: [58, 1.0, 34],
    metin: "Saz hasır ve sepet olurdu. Su kenarı yalnız içmek için değil, üretim içindi.",
    kaynakNotu: null },
  { id: "og_su_iz", ad: "Çamurdaki İzler", tip: "tarih", pos: [62, 0.9, 20],
    metin: "Islak toprak izi saklar. Kimin ne zaman geçtiği izlerden okunabilirdi.",
    kaynakNotu: null },
  { id: "og_su_taskin", ad: "Taşkın Çizgisi", tip: "doga", pos: [52, 1.1, 36],
    metin: "Kıyıdaki çakıl çizgisi suyun yükseldiği yeri gösterir. Kamp bu çizginin üstüne kurulurdu.",
    kaynakNotu: null },
  { id: "og_su_balik", ad: "Su Ürünleri", tip: "yasam", pos: [66, 1.0, 22],
    metin: "Akarsu balık da verirdi. Ancak bozkırda et ve süt daha belirleyiciydi.",
    kaynakNotu: "DOĞRULANMALI — bölgesel beslenme kaynakla eşleştirilmeli" },
  { id: "og_su_gecit", ad: "Sığ Geçit", tip: "yasam", pos: [70, 1.0, 12],
    metin: "Dere belli yerlerden geçilirdi. Geçit bilgisi yol bilgisinin parçasıydı.",
    kaynakNotu: null },
  { id: "og_su_kimiz", ad: "Serinletme", tip: "yasam", pos: [64, 1.1, 28],
    metin: "Kaplar suya batırılarak serin tutulurdu. Yaz sıcağında bu bir zorunluluktu.",
    kaynakNotu: null },
  /* ---------- ESKİ YURT YERİ ---------- */
  { id: "og_ey_iskelet", ad: "Otağ İskeleti", tip: "yapi", pos: [-34, 1.6, -66],
    metin: "Ahşap kafes kalır, keçe gider. Terk edilen yurtta önce örtü sökülürdü.",
    kaynakNotu: null },
  { id: "og_ey_kul", ad: "Ocak Külü", tip: "tarih", pos: [-30, 0.9, -64],
    metin: "Sönmüş ocak kimsenin kalmadığını gösterir. Kül dağılır ama taş kalır.",
    kaynakNotu: null },
  { id: "og_ey_katman", ad: "Toprak Katmanları", tip: "tarih", pos: [-38, 1.0, -72],
    metin: "Toprak katman katman birikir. Alt katman daha eskidir; kazı bunu okur.",
    kaynakNotu: null },
  { id: "og_ey_seramik", ad: "Seramik Parçası", tip: "tarih", pos: [-36, 0.9, -68],
    metin: "Kırık çanak bile bilgi taşır. Hamuru ve bezemesi dönemi anlatabilir.",
    kaynakNotu: null },
  { id: "og_ey_hoyuk", ad: "Höyük", tip: "tarih", pos: [-40, 2.0, -80],
    metin: "Üst üste kurulan yerleşimler tepe oluşturur. Höyük, zamanın yığılmış hâlidir.",
    kaynakNotu: null },
  { id: "og_ey_duvar", ad: "Yıkık Duvar", tip: "yapi", pos: [-44, 1.4, -76],
    metin: "Taş duvar, daha kalıcı bir yerleşimin izi olabilir. Bozkırda bu her yerde görülmez.",
    kaynakNotu: "DOĞRULANMALI" },
  { id: "og_ey_donus", ad: "Geri Dönüş", tip: "kultur", pos: [-32, 1.2, -70],
    metin: "Göç edenler dönmeyi umarak iz bırakırdı. Bazı yurtlara yıllar sonra dönülürdü.",
    kaynakNotu: null },
  { id: "og_ey_koruma", ad: "Yerinde Bırakmak", tip: "tarih", pos: [-36, 1.0, -74],
    metin: "Buluntu yerinden alınırsa bağlamı kaybolur. Bilgi çoğu zaman yerinde saklıdır.",
    kaynakNotu: null },
];

export const OGRENME_TOPLAM = OGRENME_NOKTALARI.length;
