export type OtagCevresiNotu = {
  id: string;
  sahne: "et_kurutma" | "sohbet" | "sut_sagma" | "otag_onu" | "yun_egirme";
  ad: string;
  metin: string;
  kaynakNotu: string | null;
};

export const d01OtagCevresiNotlari: OtagCevresiNotu[] = [
  {
    id: "oc_et_01",
    sahne: "et_kurutma",
    ad: "Havanın Yolu",
    metin: "İnce et parçaları, havanın dolaşabileceği aralıklarla asılmış. Böylece yüzeyler birbirine değmeden kuruyabilir.",
    kaynakNotu: null,
  },
  {
    id: "oc_et_02",
    sahne: "et_kurutma",
    ad: "Suyun Azalması",
    metin: "Kurutma, etin içindeki suyu azaltarak saklamayı kolaylaştırır. Süre, hava sıcaklığına ve neme göre değişir.",
    kaynakNotu: "FAO, Manual on Simple Methods of Meat Preservation, https://www.fao.org/4/x6932e/x6932e02.htm",
  },
  {
    id: "oc_et_03",
    sahne: "et_kurutma",
    ad: "Hasırın İşlevi",
    metin: "Hasır, parçaları topraktan uzak tutan temiz bir yüzey olabilir. Kullanılan yüzey düzenli temizlenmelidir.",
    kaynakNotu: "FAO, Manual on Simple Methods of Meat Preservation, https://www.fao.org/4/x6932e/x6932e02.htm",
  },
  {
    id: "oc_et_04",
    sahne: "et_kurutma",
    ad: "Tuz ve Nem",
    metin: "Tuz, bazı kurutma yöntemlerinde nem kaybını destekler. Miktar, ürünün tadını ve dayanıklılığını etkiler.",
    kaynakNotu: "FAO, Manual on Simple Methods of Meat Preservation, https://www.fao.org/4/x6932e/x6932e02.htm",
  },
  {
    id: "oc_et_05",
    sahne: "et_kurutma",
    ad: "Kurut Topakları",
    metin: "Kurut topakları, fermente süt ürünlerinin kurutulmuş biçimlerindendir. Kurutma, taşımayı ve saklamayı kolaylaştırabilir.",
    kaynakNotu: "FAO, The Technology of Traditional Milk Products in Developing Countries, Asia section, https://www.fao.org/4/t0251e/T0251E14.htm",
  },
  {
    id: "oc_et_06",
    sahne: "et_kurutma",
    ad: "Paylaşım Düzeni",
    metin: "Hazırlanan yiyecekler aileler arasında paylaşılmış olabilir. Dağıtım düzeni, topluluğun ihtiyaçlarına göre değişebilir.",
    kaynakNotu: "DOĞRULANMALI — D01 Oğuz obasında kurutulmuş yiyeceklerin paylaşım düzeni.",
  },
  {
    id: "oc_soh_01",
    sahne: "sohbet",
    ad: "Göz Göze Halka",
    metin: "Minderler bir halka oluşturuyor. Bu düzen, konuşanların birbirini görmesini kolaylaştırır.",
    kaynakNotu: null,
  },
  {
    id: "oc_soh_02",
    sahne: "sohbet",
    ad: "Ortadaki İkram",
    metin: "Ortadaki kap, ikramın ortak alanda sunulduğunu düşündürebilir. İçeriğini yalnız görünüşten bilemeyiz.",
    kaynakNotu: null,
  },
  {
    id: "oc_soh_03",
    sahne: "sohbet",
    ad: "Haberlerin Dolaşımı",
    metin: "Pazarlar ve konak yerleri haberlerin dolaştığı buluşma noktaları olabilir. Her haber aynı güvenilirliği taşımaz.",
    kaynakNotu: "UNESCO World Heritage Centre, Orkhon Valley Cultural Landscape, Property 1081, https://whc.unesco.org/en/list/1081/",
  },
  {
    id: "oc_soh_04",
    sahne: "sohbet",
    ad: "Dinleyerek Öğrenmek",
    metin: "Çocuklar sohbeti dinlerken yeni sözler ve öyküler duyabilir. Öğrenme, yalnız görev sırasında gerçekleşmez.",
    kaynakNotu: null,
  },
  {
    id: "oc_soh_05",
    sahne: "sohbet",
    ad: "Paylaşılan Kararlar",
    metin: "Kadınlar ve erkekler günlük kararları farklı biçimlerde paylaşmış olabilir. Roller, kaynaklar incelenmeden kesinleştirilmemelidir.",
    kaynakNotu: "DOĞRULANMALI — D01 döneminde Oğuz obasındaki gündelik karar paylaşımı ve roller.",
  },
  {
    id: "oc_soh_06",
    sahne: "sohbet",
    ad: "Misafir Minderi",
    metin: "Misafir için ayrılan minder, konukseverliği gösterebilir. Oturma sırasının anlamı kaynakla doğrulanmalıdır.",
    kaynakNotu: "DOĞRULANMALI — D01 döneminde misafirlik ve oturma düzenine ilişkin güvenilir kaynak.",
  },
  {
    id: "oc_sut_01",
    sahne: "sut_sagma",
    ad: "Temiz Kap",
    metin: "Sağım kabı temiz tutulmazsa süt çabuk bozulabilir. Kapların durulanması, ürünün korunmasına yardım eder.",
    kaynakNotu: null,
  },
  {
    id: "oc_sut_02",
    sahne: "sut_sagma",
    ad: "Yayıkta Dönüşüm",
    metin: "Yayıkta çalkalanan süt ürünü, yağın ayrılmasını sağlayabilir. Bu işlem tereyağı üretiminin temelidir.",
    kaynakNotu: "FAO, The Technology of Traditional Milk Products in Developing Countries, Butter section, https://www.fao.org/4/t0251e/t0251e15.htm",
  },
  {
    id: "oc_sut_03",
    sahne: "sut_sagma",
    ad: "Kımızın Oluşumu",
    metin: "Kısrak sütü mayalanınca kımız oluşabilir. Tat, süreye ve kullanılan mayaya göre değişir.",
    kaynakNotu: "FAO AGRIS, Kondybayev et al., Fermented Mare Milk Product (Qymyz, Koumiss), 2021, https://agris.fao.org/search/en/records/65debebf0f3e94b9e5d0dbb3",
  },
  {
    id: "oc_sut_04",
    sahne: "sut_sagma",
    ad: "Sağım Zamanı",
    metin: "Sağım zamanı, hayvanın durumuna göre ayarlanır. Yavrunun beslenmesi de dikkate alınmalıdır.",
    kaynakNotu: null,
  },
  {
    id: "oc_sut_05",
    sahne: "sut_sagma",
    ad: "Sütün Yolları",
    metin: "Süt farklı kaplara ayrılarak işlenebilir. Bazısı içilir, bazısı başka ürünlere dönüşür.",
    kaynakNotu: "FAO, The Technology of Traditional Milk Products in Developing Countries, Asia section, https://www.fao.org/4/t0251e/T0251E14.htm",
  },
  {
    id: "oc_sut_06",
    sahne: "sut_sagma",
    ad: "Hayvanı Tanımak",
    metin: "Her hayvanın davranışı ve sütü aynı değildir. Sağım yapan kişi, hayvanı dikkatle tanır.",
    kaynakNotu: null,
  },
  {
    id: "oc_ota_01",
    sahne: "otag_onu",
    ad: "Gölgelik Alan",
    metin: "Gölgelik, otağ önünde serin bir çalışma alanı oluşturur. Güneş yönü değiştikçe gölge de yer değiştirir.",
    kaynakNotu: null,
  },
  {
    id: "oc_ota_02",
    sahne: "otag_onu",
    ad: "Yakındaki Beşik",
    metin: "Beşik, bebeği günlük işlerin yakınında tutabilir. Sallanma, bebeğin sakinleşmesine yardım edebilir.",
    kaynakNotu: null,
  },
  {
    id: "oc_ota_03",
    sahne: "otag_onu",
    ad: "Kapının Yönü",
    metin: "Kapının yönü, rüzgâr ve kullanım düzeniyle ilişkili olabilir. D01 uygulaması ayrıca doğrulanmalıdır.",
    kaynakNotu: "DOĞRULANMALI — 9.–11. yüzyıl Oğuz otağlarında kapı yönlendirme uygulaması.",
  },
  {
    id: "oc_ota_04",
    sahne: "otag_onu",
    ad: "Eşyanın Yeri",
    metin: "Kaplar, tulumlar ve dokumalar belirli yerlerde tutuluyor. Düzen, sık kullanılan eşyaya erişimi kolaylaştırır.",
    kaynakNotu: null,
  },
  {
    id: "oc_ota_05",
    sahne: "otag_onu",
    ad: "Su Tulumu",
    metin: "Deri tulum, sıvı taşımak için kullanılabilir. Dikiş ve ağız kısmı sızdırmazlığı etkiler.",
    kaynakNotu: "DOĞRULANMALI — D01 dönemine uygun su tulumu örneği ve yapım tekniği.",
  },
  {
    id: "oc_ota_06",
    sahne: "otag_onu",
    ad: "Komşuluk Emeği",
    metin: "Komşu otağlar arasında araç ve emek paylaşılmış olabilir. İlişkinin biçimi topluluktan topluluğa değişebilir.",
    kaynakNotu: "UNESCO World Heritage Centre, Orkhon Valley Cultural Landscape, Property 1081, https://whc.unesco.org/en/list/1081/",
  },
  {
    id: "oc_yun_01",
    sahne: "yun_egirme",
    ad: "Lifleri Açmak",
    metin: "Yün önce ayrılır ve temizlenir. Dolaşmış lifler açıldıkça eğirme kolaylaşır.",
    kaynakNotu: null,
  },
  {
    id: "oc_yun_02",
    sahne: "yun_egirme",
    ad: "İğin Dönüşü",
    metin: "İğ ağırlaştıkça daha düzenli dönebilir. Dönüş, lifleri birbirine sararak ip oluşturur.",
    kaynakNotu: "The Metropolitan Museum of Art, Spindle Whorl, 9th–10th century, Object 38.40.1, https://www.metmuseum.org/art/collection/search/449217",
  },
  {
    id: "oc_yun_03",
    sahne: "yun_egirme",
    ad: "İpliğin Kalınlığı",
    metin: "İnce ip ile kalın ip farklı işler için uygundur. Usta, kullanım yerine göre kalınlık seçer.",
    kaynakNotu: null,
  },
  {
    id: "oc_yun_04",
    sahne: "yun_egirme",
    ad: "Renklerin Kaynağı",
    metin: "Doğal yün renkleri ipliğe çeşitlilik verir. Boyama varsa malzeme ve yöntem ayrıca incelenmelidir.",
    kaynakNotu: "DOĞRULANMALI — D01 dönemindeki Oğuz yün boyama malzemeleri ve yöntemleri.",
  },
  {
    id: "oc_yun_05",
    sahne: "yun_egirme",
    ad: "İplikten Dokumaya",
    metin: "Eğrilen ip, dokuma için hazırlanır. Bir kilim, sayısız ipin düzenli birleşmesiyle oluşur.",
    kaynakNotu: "The Metropolitan Museum of Art, Spindle Whorl, 9th–10th century, Object 38.40.1, https://www.metmuseum.org/art/collection/search/449217; The Metropolitan Museum of Art, Textile with Confronted Horses in Roundels, 8th–9th century, Object 2006.173, https://www.metmuseum.org/art/collection/search/73207",
  },
  {
    id: "oc_yun_06",
    sahne: "yun_egirme",
    ad: "Paylaşılan Beceri",
    metin: "Yün işi farklı yaşlardaki kişilerin katkısıyla ilerleyebilir. Sahnede görevler beceriye göre paylaşılabilir.",
    kaynakNotu: null,
  },
];
